### ISSUE TITLE
Provide custom rollup config

### ISSUE THREAD

**Issue by mikenikles** [bahmutov/cy-rollup#2]
The `rollup.config.js` is currently hard-coded, which works well for Svelte applications.

In the case of Sapper (https://sapper.svelte.dev), the default `rollup.config.js` has a slightly different format. In short, it's split into three sections:
* `client`
* `server`
* `serviceworker`

It'd be nice to have the rollup config file name configurable. Along the lines of:

```js
// cypress/plugins/index.js
const options = {
  rollupConfigFile: 'cypress/rollup.config.js'
}

on('file:preprocessor', require('@bahmutov/cy-rollup')(options))
```

With a config file like this:

```js
// cypress/rollup.config.js
import rollupConfig from '../rollup.config.js'
export default rollupConfig.client
```

I'm happy to open a PR, but wanted to discuss first. What do you think?

Context: https://github.com/sveltejs/sapper-template/blob/master/rollup.config.js

**Comment by bahmutov** [comment]
Yes, definitely a good idea, open a PR
